### ISSUE TITLE
Video does not show up on the list of videos.

### ISSUE THREAD

**Issue by HappyHub1** [Zahaib/DailyMotionUpload#1]
Hi. 

I found your post on stackexchange and have been trying to figure out how to get it to work for the past day. Currently it uploads the video but it stays at encoding forever and does not show up on my list of videos. I noticed that you got it to work and was wondering what you did to make that happen.

**Comment by Zahaib** [comment]
Hi,

I did not run in to the same problem, usually my videos were small so they were fine.

I was just testing my own code and that also seems to be failing, perhaps DM has changed the parameters they need in their API calss, that's probably the reason the code is breaking, although I haven't confirmed this.

**Comment by HappyHub1** [comment]
I think I have gotten it to work. I looked at the dailymotion API again and made some changes.

http://pastebin.com/2rFcyyML

It's currently encoding and showing up on my video list.

**Comment by Zahaib** [comment]
Thats cool, glad that you got it to work. Please feel free to push an update to repo, I've added you as a collaborator.

Thanks.
