### ISSUE TITLE
Getting error: sed: -e expression #1, char 17: unknown option to `s'

### ISSUE THREAD

**Issue by ahmadwalid231** [Zahaib/DailyMotionUpload#4]
Hello,
1st of all thanks for the great work. 2ndly, I'm having an issue while uploading multiple videos from the list. The error is;
sed: -e expression #1, char 17: unknown option to `s'
Publishing video...
Video uploaded with id more_info
sed: -e expression #1, char 17: unknown option to`s'
Publishing video...
and it goes on for every video. While uploading a single video, I don't have any problem. In the list1.txt and list2.txt videos are something like this;
"forexample1.mp4" /root/converted/forexample1.mp4 sport
"forexample2.mp4" /root/converted/forexample2.mp4 sport

I have no idea, what am I doing wrong.

**Comment by Zahaib** [comment]
Hi,

The way multiple upload section is implemented right now it makes an assumption that the videos are in the same directory as the dmUpload.sh script. I haven't re-produced your error but by looking at the error message that is being displayed, it seems that the slashes in the video path are causing trouble.

Please try by putting the dmUpload.sh in the same directory as the videos and remove the /root/converted/ from your file names. Let me know if this works out for you, for a quick fix that's fine but in the future I will fix the implementation to take care of a full path.

**Comment by ahmadwalid231** [comment]
Hello Zahaib, 
thanks for quick reply. I moved the dmUpload.sh in the same directory as videos, now I don't get that error. But now it gives me error;
cat: list2.txt: No such file or directory
Though list2.txt file exist and is the same directory as everything else. and when I try to remove the list2.txt from the command line, then I get no error, but it seems to be doing nothing and the execution doesn't stop, until I stop it manually with ctrl+c.
My command is;
./dmUpload.sh -u user@gmail.com -p mypassword -k myapi_key -s myapi_secret -l en --multiple list1.txt
