### ISSUE TITLE
realpath

### ISSUE THREAD

**Issue by kypdk** [Zahaib/DailyMotionUpload#6]
basename: invalid option -- 't'
Try 'basename --help' for more information.
realpath: invalid option -- 'q'
Usage:
 realpath [-s|--strip] [-z|--zero] filename ...
 realpath -h|--help
 realpath -v|--version
Video File not found: !

**Comment by Zahaib** [comment]
@marcsello can you please take a look at this. BTW realpath doesn't come out of the box on a Mac. So if the issue is because of realpath we need to change that.

**Comment by marcsello** [comment]
@tutked What operating system you on?
