### ISSUE TITLE
Auth failure

### ISSUE THREAD

**Issue by KenSharp** [Zahaib/DailyMotionUpload#7]
I don't know if I'm doing this wrong, but I cannot get this to authorise.

```
$ dmUpload.sh -u "User Name" -p $(</run/user/1001/pw) -k <removed> -s <removed> -c Music -t TEST My_Video.mp4
...
$ cat out.txt 
{"error":{"more_info":"https:\/\/developer.dailymotion.com\/api#error-codes","code":400,"message":"Invalid Authorization header format.","type":"invalid_parameter"}}
```
Looking at the API [documentation](https://developer.dailymotion.com/api) this does indeed seem to be incorrect.

Furthermore the script should immediately fail because it isn't doing anything useful, just thinks it is.

`Video uploaded with id more_info`

**Comment by Zahaib** [comment]
Can you please let me know the OS you are on? The script will break if you are using Mac because support for some of the `cut` flags on Mac OS is different.

**Comment by KenSharp** [comment]
Hello.

```
$ lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-ia32:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-ia32:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
```
$ cut --version
cut (GNU coreutils) 8.25

$ dpkg -s coreutils
Package: coreutils
Essential: yes
Status: install ok installed
Priority: required
Section: utils
Installed-Size: 6408
Maintainer: Ubuntu Developers <snip>
Architecture: i386
Multi-Arch: foreign
Version: 8.25-2ubuntu3~16.04
Replaces: mktemp, realpath, timeout
Pre-Depends: libacl1 (>= 2.2.51-8), libattr1 (>= 1:2.4.46-8), libc6 (>= 2.17), libselinux1 (>= 2.1.13)
```

**Comment by Zahaib** [comment]
OK, thanks. Let me reproduce the issue and push an update.

**Comment by Zahaib** [comment]
OK, I pushed an update that works for me. The problem was with the response returned by the file upload request. There seem to be additional fields added to the response which were breaking the script. I've made it a little less brittle right now so that it continues to work if in future more fields are added. To make it more flexible either I make it require a JSON parser like `jq` or it would need a bigger overhaul.

Please do a fresh pull and let me know if you can get it to work now.

**Comment by KenSharp** [comment]
It won't work but...
I tried getting the access token a few times and this worked - twice! Every time I've tried since it fails with `{"error":"invalid_grant","error_description":"Invalid credentials."}` Yet the identical credentials gave me an access token twice so I have no idea what is going on. I can't see it being a script problem.

I'll let something time out at the server end and try again.

**Comment by KenSharp** [comment]
Looking good!

The first tag is set incorrectly as $FILENAME$TAG1 but that should be easy to solve. ;)
